# Generated by Django 5.1.1 on 2024-11-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Andra Pradesh', 'Andra Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('U.P', 'U.P'), ('M.P', 'M.P'), ('Delhi', 'Delhi'), ('Maharastra', 'Maharastra')], max_length=200),
        ),
    ]
